import { Link } from 'react-router-dom'
import { ArrowUpRight, ArrowRight, Code2, Globe2, Sparkles, Sprout, Check, Coffee, Building2, ShoppingBag, PartyPopper, Camera, Rocket } from 'lucide-react'
import HorizonHeroSection from '@/components/ui/horizon-hero-section'
import { Reveal, TiltCard } from '@/components/ui/interactive'

const industries = [{ name: 'Cafés & restaurants', icon: Coffee }, { name: 'Events & experiences', icon: PartyPopper }, { name: 'Real estate', icon: Building2 }, { name: 'Retail & local', icon: ShoppingBag }, { name: 'Creators & brands', icon: Camera }, { name: 'Startups & businesses', icon: Rocket }]

export default function Home() {
  return <main>
    <HorizonHeroSection />
    <div className="brand-strip" role="group" aria-label="Our approach"><span>GOOD DESIGN. GOOD ENERGY.</span><i>✳</i><span>BUILT AROUND YOUR BUSINESS</span><i>✳</i><span>A LITTLE DIFFERENT. A LOT YOU.</span><i>✳</i><span>LET’S MAKE SOMETHING GOOD</span><i>✳</i></div>
    <section className="section container services-section" id="services">
      <Reveal className="section-header"><div><p className="eyebrow">01 / WHAT WE DO</p><h2 className="section-heading">Your next chapter.<br />Our <span className="serif-word">happy place.</span></h2></div><p className="section-intro">Good digital things start with understanding you.<br />We bring your business to life, one thoughtful<br className="desktop-br" /> detail at a time.</p></Reveal>
      <div className="service-grid">
        <Reveal><TiltCard className="service-card web-service"><div className="service-card-top"><span className="icon-box"><Code2 size={23} /></span><span className="card-number">01</span></div><div className="mini-browser" aria-hidden="true"><div className="browser-toolbar"><i /><i /><i /><span>your-next-big-thing.com</span></div><div className="browser-art"><span className="browser-kicker">MADE FOR YOU</span><strong>Hello,<br /><em>possibility.</em></strong><span className="browser-button">Make yourself at home ↗</span><div className="browser-flower"><i /><i /><i /><i /><i /><i /><b /></div></div></div><h3>Websites that feel like you.</h3><p>From clean portfolios to powerful web applications. Beautiful, responsive and built around your business.</p><Link className="card-link" to="/services#websites">Explore websites <span><ArrowUpRight size={20} /></span></Link></TiltCard></Reveal>
        <Reveal><TiltCard className="service-card social-service"><div className="service-card-top"><span className="icon-box"><Sparkles size={23} /></span><span className="card-number">02</span></div><div className="social-art" aria-hidden="true"><div className="social-tile tile-one"><span>fresh<br />perspectives.</span><i>✳</i><small>YOUR DAILY DOSE OF GOOD</small></div><div className="social-tile tile-two"><span>let’s<br /><em>grow.</em></span><div className="social-leaf" /></div><div className="social-like">♡ &nbsp; A little more connection</div></div><h3>A social presence with soul.</h3><p>Monthly content planning, creatives and copy that keep your brand showing up as its best self.</p><Link className="card-link" to="/services#social">Explore social media <span><ArrowUpRight size={20} /></span></Link></TiltCard></Reveal>
        <Reveal><TiltCard className="service-card combo-service"><div className="service-card-top"><span className="icon-box"><Sprout size={23} /></span><span className="card-number">03</span></div><div className="combo-art" aria-hidden="true"><div className="combo-orb orb-web"><Globe2 size={36} /></div><div className="combo-orb orb-social"><Sparkles size={36} /></div><span className="combo-plus">+</span><span className="combo-tag">ONE BRAND. EVERYWHERE.</span></div><h3>Better, together.</h3><p>Your website and social media, perfectly in sync. One creative direction. A more connected brand.</p><Link className="card-link" to="/services#together">Meet the perfect pair <span><ArrowUpRight size={20} /></span></Link></TiltCard></Reveal>
      </div>
      <Reveal className="pricing-note"><Check size={15} /><span>Made to fit your goals. Quoted to fit your project.</span><Link to="/contact">Let’s find your fit <ArrowUpRight size={14} /></Link></Reveal>
    </section>
    <section className="growth-section" id="approach">
      <div className="container growth-layout">
        <Reveal className="growth-art" ><div className="growth-orbit" /><div className="pearl pearl-large" /><div className="pearl pearl-small" /><div className="growth-leaf leaf-a" /><div className="growth-leaf leaf-b" /><div className="growth-leaf leaf-c" /><span className="growth-art-label">A LITTLE CARE GOES A LONG WAY.</span><span className="growth-cross cross-a">+</span><span className="growth-cross cross-b">+</span></Reveal>
        <Reveal className="growth-copy"><p className="eyebrow">A LITTLE ABOUT US</p><h2 className="section-heading">Small by choice.<br /><span className="serif-word">Thoughtful</span> by nature.</h2><p>We’re Pearl Panda. A digital studio for businesses ready to show up a little differently.</p><p>We believe your online world should feel as considered as the business you’ve built. So we listen closely, think playfully and make every detail count.</p><Link className="button button-secondary" to="/about">Get to know your pandas <ArrowUpRight size={17} /></Link></Reveal>
      </div>
    </section>
    <section className="section container industries-section">
      <Reveal className="section-header"><div><p className="eyebrow">02 / WHO WE GROW WITH</p><h2 className="section-heading">Your world.<br />Our <span className="serif-word">playground.</span></h2></div><Link className="text-link" to="/industries">Explore industries <ArrowUpRight size={17} /></Link></Reveal>
      <div className="industry-grid">{industries.map(({ name, icon: Icon }, i) => <Reveal key={name}><Link className="industry-card" to={`/industries#industry-${i}`}><span className="industry-icon"><Icon size={29} strokeWidth={1.4} /></span><h3>{name}</h3><ArrowUpRight className="industry-arrow" size={18} /></Link></Reveal>)}</div>
    </section>
    <section className="section container work-section">
      <Reveal className="section-header"><div><p className="eyebrow">03 / A TASTE OF POSSIBILITY</p><h2 className="section-heading">Ideas with a<br /><span className="serif-word">little extra.</span></h2></div><div><p className="work-disclaimer">A few concept explorations.<br />A feel for what we can imagine together.</p><Link className="text-link" to="/work">Step into the studio <ArrowUpRight size={17} /></Link></div></Reveal>
      <div className="work-preview-grid"><Reveal><Link className="work-preview cafe-preview" to="/work"><span className="preview-type">WEBSITE CONCEPT</span><div className="cafe-concept"><div className="cafe-nav">morrow<span>GOOD COFFEE. SLOW MORNINGS.</span></div><h3>Take a<br /><em>little pause.</em></h3><div className="coffee-cup"><i /></div><span className="cafe-pill">Find your morning ↗</span></div><div className="preview-caption"><span>Morrow Café<small>A warmer welcome, online.</small></span><ArrowUpRight /></div></Link></Reveal><Reveal><Link className="work-preview social-preview" to="/work"><span className="preview-type">SOCIAL MEDIA CONCEPT</span><div className="social-concept"><div className="concept-poster poster-peach"><small>THE EVERYDAY EDIT</small><strong>less scroll.<br /><em>more soul.</em></strong><i>✳</i></div><div className="concept-poster poster-green"><small>GROW AT YOUR OWN PACE</small><strong>good things<br /><em>take root.</em></strong><div className="poster-sun" /></div></div><div className="preview-caption"><span>The Everyday Edit<small>A fresh perspective in every post.</small></span><ArrowUpRight /></div></Link></Reveal></div>
    </section>
    <section className="container cta-wrap"><Reveal className="cta-card"><span className="cta-spark" aria-hidden="true">✳</span><p className="eyebrow">EVERY GREAT THING STARTS WITH A HELLO</p><h2>Ready to grow<br />something <span className="serif-word">good?</span></h2><Link to="/contact" className="button button-cream">Let’s start a conversation <ArrowUpRight size={19} /></Link><span className="cta-footnote">Your idea. Our curiosity. A good place to start.</span><div className="cta-orbit" aria-hidden="true" /></Reveal></section>
  </main>
}
